// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjcimyO4DurQW7GnEdWSGo-QE6HwtL7I',
    appId: '1:149121065823:web:762e665712afb6026c4cea',
    messagingSenderId: '149121065823',
    projectId: 'sgp-l-47bde',
    authDomain: 'sgp-l-47bde.firebaseapp.com',
    storageBucket: 'sgp-l-47bde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdiFo-uz8KmYCsW_pg4-NIp8odfRccXM',
    appId: '1:149121065823:android:2768705ae67b35a06c4cea',
    messagingSenderId: '149121065823',
    projectId: 'sgp-l-47bde',
    storageBucket: 'sgp-l-47bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5l4fx4BLcTfR3PsardXvdTBDjPgdS89c',
    appId: '1:149121065823:ios:0fff3452b861cfd66c4cea',
    messagingSenderId: '149121065823',
    projectId: 'sgp-l-47bde',
    storageBucket: 'sgp-l-47bde.appspot.com',
    androidClientId: '149121065823-peu48l9cud3ejhur52bkab3d89p010v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5l4fx4BLcTfR3PsardXvdTBDjPgdS89c',
    appId: '1:149121065823:ios:0fff3452b861cfd66c4cea',
    messagingSenderId: '149121065823',
    projectId: 'sgp-l-47bde',
    storageBucket: 'sgp-l-47bde.appspot.com',
    androidClientId: '149121065823-peu48l9cud3ejhur52bkab3d89p010v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcjcimyO4DurQW7GnEdWSGo-QE6HwtL7I',
    appId: '1:149121065823:web:8900d446e13f5d5b6c4cea',
    messagingSenderId: '149121065823',
    projectId: 'sgp-l-47bde',
    authDomain: 'sgp-l-47bde.firebaseapp.com',
    storageBucket: 'sgp-l-47bde.appspot.com',
  );

}